version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: simple-bank_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: simple-bank_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: simple-bank_database
    restart: always
    environment:
      POSTGRES_DB: bank_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
